services:
  - type: web
    name: permit-pdf-extractor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: permit_automation/creds/service-account.json
